server:
  port: 8084

spring:
  application:
    name: peminjaman-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587             
    username: mfebrianti422@gmail.com 
    password: fbxjajpprmnlbxsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      register-with-eureka: true
      fetch-registry: true